package Abstract;

import Entities.Customer;

public abstract class BaseCustomerManager implements CustomerService {
	
	/* EÐER BU ABSTRACT SINIF OLMASAYDI YANÝ SADECE INTERFACE OLSAYDI HER BÝR MANAGER ÝÇÝN AYRI AYRI VERÝTABANINA EKLEME 
	KODU YAZILACAKTI.INTERFACE ÝLE YAPMAK ÝÞE YARARDI FAKAT UÐRAÞTIRIRDI. ORTAK OPERASYONLARI OLAN MANAGERLERÝ TEK BÝR BASE ABSTRACT SINIFINDA
	 TOPLARSAK ORTAK OPERASYONLARI TEK ELDEN YÖNETMÝÞ OLURUZ KISACASI ORTAK OPERASYONLARI OLAN SINIFLARI BASE SINIFTA TOPLAMAK
	 ÇOK DAHA AVANTAJLI OLACAKTIR */
	
	@Override
	public void Add(Customer customer) {
		System.out.println("Müþteri eklendi");
	}
}
